version: '3'
services:
  bt:
    image: linuxserver/qbittorrent
    restart: unless-stopped
    environment:
      - WEBUI_PORT=8080
      - TZ=Asia/Shanghai
      - UMASK_SET=022
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 21756:21756
      - 21756:21756/udp
      - 8080:8080

